# TIME SERIES DATABASE
TIME_SERIES_DATABASE_NAME = 'cryptowatch-db'
TIME_SERIES_TABLE_NAME = 'metrics'
ONE_GB_IN_BYTES = 1073741824
# Assuming the price of query is $0.01 per GB
QUERY_COST_PER_GB_IN_DOLLARS = 0.01 

# CRYPTOWATCH
CRYPTOWATCH_API_KEY = 'EH800R6V0238D8B7UM05'

#AWS
AWS_REGION = 'us-east-1'

